Need for new dockerfile - fullstack embedded app agent #5
EclipseFdn/dockerfiles pull request #6
Opened 2021-05-31 19:42 UTC by autumnfound

2021-05-31 19:44 UTC, autumnfound commented
The usage of the echo command pulls in the previous release package data to be used in conjunction with the current release. This gives us a wider range of packages to choose from that include the current node version that we support for the hugo solstice theme. If we moved to the latest LTS (14.X.X) we would be able to drop that command and the version less than clause for nodejs.

2021-06-02 15:35 UTC, mbarbero requested changes

2021-06-02 15:35 UTC, mbarbero commented on stack-build-agent/h79.1-n12.22.1-jdk11/Dockerfile
> +RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.12/main' >> /etc/apk/repositories
Best practice: do not invoke several `RUN` commands in a row if not absolutely needed as each one create a new layer. 

```
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.12/main' >> /etc/apk/repositories \
    && apk add --no-cache \
    make \
    ...
```

instead.

2021-06-03 17:23 UTC, mbarbero approved these changes

2021-06-04 13:53 UTC, merged